spring:
  application:
    name: teste-2
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/admin
  kafka:
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      bootstrap-servers: localhost:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: io.github.rafaelpeinado.teste_2.domain.model
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      schema:
        registry:
          url: http://localhost:8085